EduWeb/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EduWeb.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

EduWeb/Controllers/AcountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EduWeb.Controllers
{
    public class AcountController : Controller
    {
        // GET: Acount
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }
    }
}

EduWeb/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EduWeb.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

EduWeb/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EduWeb.Controllers
{
    public class CoursesController : Controller
    {
        // GET: Courses
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Wordpress_courses()
        {
            return View();
        }
        public ActionResult Uxiu_courses()
        {
            return View();
        }
        
        public ActionResult Python_courses()
        {
            return View();
        }
        public ActionResult Photoshop_courses()
        {
            return View();
        }
        public ActionResult Java_courses()
        {
            return View();
        }
        public ActionResult Html_courses()
        {
            return View();
        }
    }
}

EduWeb/Views/Shared/_Layout.cshtml
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Edumark</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/img/favicon.png">
    <!-- Place favicon.ico in the root directory -->
    <!-- CSS here -->
    <link rel="stylesheet" href="~/Scripts/css/bootstrap.min.css">
    <link href="~/Scripts/css/themify-icons.css" rel="stylesheet" />
    <link href="~/Scripts/fontawesome-free-5.14.0-web/css/svg-with-js.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Scripts/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Scripts/css/magnific-popup.css">
    <link rel="stylesheet" href="~/Scripts/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Scripts/css/themify-icons.css">
    <link rel="stylesheet" href="~/Scripts/css/nice-select.css">
    <link rel="stylesheet" href="~/fonts/flaticon.css" />
    <link rel="stylesheet" href="~/Scripts/css/gijgo.css">
    <link rel="stylesheet" href="~/Scripts/css/animate.css">
    <link rel="stylesheet" href="~/Scripts/css/slicknav.css">
    <link href="~/Scripts/fontawesome-free-5.14.0-web/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Scripts/css/style.css">
    <!-- <link rel="stylesheet" href="~/Scripts/css/responsive.css"> -->
</head>
<body>
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid p-0">
                    <div class="row align-items-center no-gutters">
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo-img">
                                <a href="@Url.Action("Index","Home")">
                                    <img src="~/Content/img/logo.png" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-7 col-lg-7">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li>
                                            <a class="" href="@Url.Action("Index","Home")">home</a>
                                        </li>
                                        <li>
                                            <a class="" href="@Url.Action("Index","Courses")">Courses</a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Index","Home")">Library <i class=""></i></a>
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Index","Leturers")">Lecturers <i class=""></i></a>
                                        </li>
                                        <li><a href="@Url.Action("Index","About")">About</a></li>
                                        <li>
                                            <a href="@Url.Action("Blog","Blog")">Blog <i class=""></i></a>
                                        </li>
                                        <li><a href="@Url.Action("Index","Contact")">Contact</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                            <div class="log_chat_area d-flex align-items-center">
                                <div class="live_chat_btn login">
                                    <a href="@Url.Action("Login","Acount")" class="boxed_btn_blue">

                                        <span>log in</span>
                                    </a>
                                </div>
                                <div class="live_chat_btn">
                                    <a class="boxed_btn_orange" href="@Url.Action("Payment","Cart")">

                                        <span>cart</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->
    @RenderBody()
    <!-- footer -->
    <footer class="footer footer_bg_1" style="background-image: url(../../Content/img/banner/footer_bg.png)">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="~/Content/img/logo.png" alt="">
                                </a>
                            </div>
                            <p>
                                Education - Training is a type of activity that plays a particularly important role in the development of every country in the world. Entering the 21st century, with the strong development of science and technology, the industrial economy.
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="fab fa-facebook-f"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="ti-twitter-alt"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-youtube-play"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 offset-xl-1 col-md-6 col-lg-3">
                        <div class="footer_widget">
                            <h3 class="footer_title">
                                Courses
                            </h3>
                            <ul>
                                <li><a href="#">Wordpress</a></li>
                                <li><a href="#">Photoshop</a></li>
                                <li><a href="#">Python</a></li>
                                <li><a href="#">Java XD</a></li>
                                <li><a href="#">UI/UX</a></li>
                                <li><a href="#">HTML</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget">
                            <h3 class="footer_title">
                                Resourches
                            </h3>
                            <ul>
                                <li><a href="#">Free Adobe XD</a></li>
                                <li><a href="#">Tutorials</a></li>
                                <li><a href="#">About</a></li>
                                <li><a href="#"> About</a></li>
                                <li><a href="#"> Contact</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget">
                            <h3 class="footer_title">
                                Address
                            </h3>
                            <p>
                                248, Hoang quoc viet, Nam tu liem,  Ha Noi <br>
                                038806388 <br>
                                edumark@contact.com
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer -->
    <!-- form itself end-->
    <form id="test-form" class="white-popup-block mfp-hide">
        <div class="popup_box ">
            <div class="popup_inner">
                <div class="logo text-center">
                    <a href="#">
                        <img src="~/Content/img/form-logo.png" alt="">
                    </a>
                </div>
                <h3>Sign in</h3>
                <form action="#">
                    <div class="row">
                        <div class="col-xl-12 col-md-12">
                            <input type="email" placeholder="Enter email">
                        </div>
                        <div class="col-xl-12 col-md-12">
                            <input type="password" placeholder="Password">
                        </div>
                        <div class="col-xl-12">
                            <button type="submit" class="boxed_btn_orange">Sign in</button>
                        </div>
                    </div>
                </form>
                <p class="doen_have_acc">
                    Don’t have an account? <a class="dont-hav-acc" href="#test-form2">Sign Up</a>
                </p>
            </div>
        </div>
    </form>
    <!-- form itself end -->
    <!-- form itself end-->
    <form id="test-form2" class="white-popup-block mfp-hide">
        <div class="popup_box ">
            <div class="popup_inner">
                <div class="logo text-center">
                    <a href="#">
                        <img src="~/Content/img/form-logo.png" alt="">
                    </a>
                </div>
                <h3>Resistration</h3>
                <form action="#">
                    <div class="row">
                        <div class="col-xl-12 col-md-12">
                            <input type="email" placeholder="Enter email">
                        </div>
                        <div class="col-xl-12 col-md-12">
                            <input type="password" placeholder="Password">
                        </div>
                        <div class="col-xl-12 col-md-12">
                            <input type="Password" placeholder="Confirm password">
                        </div>
                        <div class="col-xl-12">
                            <button type="submit" class="boxed_btn_orange">Sign Up</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </form>
    <!-- form itself end -->
    <!-- JS here -->
    <script src="~/Scripts/js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="~/Scripts/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/js/popper.min.js"></script>
    <script src="~/Scripts/fontawesome-free-5.14.0-web/js/all.js"></script>
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <script src="~/Scripts/js/owl.carousel.min.js"></script>
    <script src="~/Scripts/js/isotope.pkgd.min.js"></script>
    <script src="~/Scripts/js/ajax-form.js"></script>
    <script src="~/Scripts/js/waypoints.min.js"></script>
    <script src="~/Scripts/js/jquery.counterup.min.js"></script>
    <script src="~/Scripts/js/imagesloaded.pkgd.min.js"></script>
    <script src="~/Scripts/js/scrollIt.js"></script>
    <script src="~/Scripts/js/jquery.scrollUp.min.js"></script>
    <script src="~/Scripts/js/wow.min.js"></script>
    <script src="~/Scripts/js/nice-select.min.js"></script>
    <script src="~/Scripts/js/jquery.slicknav.min.js"></script>
    <script src="~/Scripts/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Scripts/js/plugins.js"></script>
    <script src="~/Scripts/js/gijgo.min.js"></script>

    <!--contact js-->
    <script src="~/Scripts/js/contact.js"></script>
    <script src="~/Scripts/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/Scripts/js/jquery.form.js"></script>
    <script src="~/Scripts/js/jquery.validate.min.js"></script>
    <script src="~/Scripts/js/mail-script.js"></script>

    <script src="~/Scripts/js/main.js"></script>
    @RenderSection("jsFooter", required: false)
</body>
</html>

EduWeb/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>